[package]
name = "example-minimal"
publish = false
license-file.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
lazy_link = { version = "*", path = "../../lazy_link" }
